/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Liveness probe for the Docker HEALTHCHECK.
     *
     *     Returns:
     *         A dictionary indicating the health status.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Chat
     * @description One-shot request/response: run the graph, return the final answer.
     *
     *     Args:
     *         payload: The request body containing the chat message and session ID.
     *         graph: The graph instance to use for processing the request.
     *
     *     Returns:
     *         A ChatResponse object containing the assistant's reply, resolved language,
     *         and routed intent.
     */
    post: operations['chat_chat_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * ChatRequest
     * @description Body of POST /chat and the JSON envelope sent over /ws/chat.
     */
    ChatRequest: {
      /**
       * Session Id
       * @description Stable id that groups turns into one conversation.
       */
      session_id: string
      /**
       * Message
       * @description The user's turn, plain text.
       */
      message: string
      /**
       * Device Id
       * @description Which device this turn came from (optional).
       */
      device_id?: string | null
    }
    /**
     * ChatResponse
     * @description Body of the POST /chat reply.
     */
    ChatResponse: {
      /**
       * Reply
       * @description The assistant's final answer.
       */
      reply: string
      /**
       * Lang
       * @description Resolved language tag, e.g. 'pt-BR'.
       */
      lang: string | null
      /**
       * Route
       * @description Routed intent, e.g. 'knowledge'.
       */
      route: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  chat_chat_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChatResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
